import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Super Dope Portfolio</title>
        <meta name="description" content="Generated by me, because I am a coder!" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>My Portfolio</h1>
        
    </div>
  )
}